# Generated by Django 3.1.1 on 2020-09-25 07:48

from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donorlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('bloodgroup', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=70)),
            ],
        ),
    ]
