# Generated by Django 3.1.1 on 2020-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBM', '0002_auto_20200927_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='requesterlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('doctor_name', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField()),
            ],
        ),
    ]
