# Generated by Django 3.1.1 on 2020-10-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBM', '0003_requesterlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorform',
            name='address',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='donorform',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='donorform',
            name='blood_group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donorform',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
