# Generated by Django 3.1.1 on 2020-10-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBM', '0004_auto_20201002_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesterlist',
            old_name='contact_number',
            new_name='mobile_number',
        ),
        migrations.AddField(
            model_name='requesterlist',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requesterlist',
            name='patient_address',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='requesterlist',
            name='blood_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requesterlist',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requesterlist',
            name='patient_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
