# Generated by Django 3.1.1 on 2020-10-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBM', '0005_auto_20201002_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesterlist',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requesterlist',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requesterlist',
            name='patient_address',
            field=models.CharField(default='', max_length=90),
        ),
    ]
