# Generated by Django 3.1.1 on 2020-10-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBM', '0006_auto_20201002_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesterlist',
            name='patient_address',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
