# Generated by Django 3.1.1 on 2020-10-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBM', '0007_auto_20201002_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorform',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
