# Generated by Django 3.1.1 on 2020-10-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBM', '0008_auto_20201003_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorform',
            name='address',
        ),
    ]
