# Generated by Django 3.1.1 on 2020-10-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBM', '0010_donorform_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorform',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
